### ISSUE TITLE
Droxy for ARM

### ISSUE THREAD

**Issue by ulm0** [alash3al/droxy#1]
Hello, just found your project at Golang News, and i'm interested in testing it out, so for now i built the binary on a RPi3, tomorrow i hope i have enough time to test it properly. Just dropping by to leave the arm binary in case you want to distribute it as well.

[droxy-arm32.tar.gz](https://github.com/alash3al/droxy/files/1066214/droxy-arm.tar.gz)

Cheers!

EDIT: 
binary compressed with `upx-ucl` :
[droxy-arm32.tar.gz](https://github.com/alash3al/droxy/files/1066447/droxy-arm32.tar.gz)

**Comment by alash3al** [comment]
Thanks @klud1 , I'll link this issue in the releases ..

As a side notice,
to build your binary and make it smaller as possible,
just add this to your build command `-ldflags="-s -w"`, then use `upx-ucl`
this will compress your binary from ~7MB to ~1.5MB,
i think this will help you specially for embedded systems ...

**Comment by ulm0** [comment]
@alash3al You're absolutely right, forgot about it, my bad, will build it and upload it again. Thanks for the reminder!

**Comment by ulm0** [comment]
@alash3al Just updated the issue and added the binary.

**Comment by alash3al** [comment]
Thank you @klud1 ,
I've linked this issue in the [releases page](https://github.com/alash3al/droxy/releases/tag/v2.0), as ARM source, so that anyone can compile his ARM version and upload it here.
More info about ARM compiling on [Golang Official Site](https://github.com/golang/go/wiki/GoArm)
```
GOOS =??
GOARCH=ARM|ARM64
GOARM=??
```

**Comment by ulm0** [comment]
Great, thanks @alash3al going to give it a try later, and see how it goes with some services i got running, i'm thinking of making a docker image out of it as wel.

**Comment by alash3al** [comment]
About the docker image, yes I think it will be great, I'll try building it in my free time, I'll use alpine + droxy-linux-64bit to make it small as possible.
Thanks for your response,  
if you have any suggestions or issues, just open an issue,
and it will be great if you come back and tell us you experience about using droxy.

**Comment by ulm0** [comment]
Sure, I use alpine as well, also like lightweight images!
Absolutely, I'll test it and let you know if any idea comes to my mind asap.

**Comment by ulm0** [comment]
Hey, back again. Been testing it (without TLS yet), great job, the usage is pretty straightforward, though it lacks some things(such as a kind of proxy_set_header pass to container/service like in Nginx ).

E.g. (nginx sample)
```nginx
proxy_set_header Strict-Transport-Security "max-age=31536000";
# includeSubDomains; preload;";
proxy_set_header X-Content-Type-Options nosniff;
proxy_set_header X-Frame-Options "SAMEORIGIN";
proxy_set_header X-XSS-Protection "1; mode=block";
proxy_set_header X-Robots-Tag none;
proxy_set_header X-Download-Options noopen;
proxy_set_header X-Permitted-Cross-Domain-Policies none
```
On the other hand, been reading a few docs of https://github.com/urfave/cli, you can use it to improve the cli, flags, args and so on.

E.g. (In this example I use a `VERSION` file that contains a `2.0` string within; off-topic: this file can ease the version bump and build automation processes later on)
```golang
droxy := cli.NewApp()
droxy.Name = "Droxy"
droxy.Usage = "Proxy for Docker containers"
droxy.Description = "A transparent standalone HTTP/S reverse proxy for Docker containers."
droxy.UsageText = "droxy [global options] command [command options] [arguments...]"
droxy.Version = func() string {
	f, _ := os.Open("./VERSION")
	defer f.Close()
	i, _ := f.Stat()
	v := make([]byte, i.Size())
	_, _ = f.Read(v)
	version := string(v)
	return version
}()
droxy.Author = "alash3al"
droxy.Run(os.Args)
```
This will output something like this
```sh
NAME:
   Droxy - Proxy for Docker containers

USAGE:
   droxy [global options] command [command options] [arguments...]

VERSION:
   2.0

DESCRIPTION:
   A transparent standalone HTTP/S reverse proxy for Docker containers.

AUTHOR:
   alash3al

COMMANDS:
     help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --help, -h     show help
   --version, -v  print the version
```
One more thing, I forked your project to my gitlab account (group actually) in order to use gitlab ci to automate the build process and the coming docker images. You can join if You want to and push the changes from gitlab to your repo here, so people won't lose track of your work, or simply push to group i have here in github the same name as in gitlab. 
This is the repo: https://gitlab.com/ruway/droxy

**Comment by alash3al** [comment]
Thanks for your suggestions, 
I'll try to add more features in my next free time.
